/* математические макросы */
#define _SQR(w) ((w)*(w)) // квадрат числа

#define	pr1Speed_X Left[0]
#define	pr1Speed_Y Left[1]
#define	pr1Speed_Z Left[2]
#define	pr1Point_X Left[3]
#define	pr1Point_Y Left[4]
#define	pr1Point_Z Left[5]
#define	pr1omegaX   Left[6]
#define	pr1omegaY   Left[7]
#define	pr1omegaZ   Left[8]
#define	pr1ro_rg    Left[9]
#define	pr1lamda_rg Left[10]
#define	pr1mu_rg    Left[11]
#define	pr1nu_rg    Left[12]
#define pr1B		Left[13]
#define pr1L		Left[14]
#define pr1H		Left[15]

#define	Speed_X el[0]
#define	Speed_Y el[1]
#define	Speed_Z el[2]
#define	Point_X el[3]
#define	Point_Y el[4]
#define	Point_Z el[5]
#define	omegaX   el[6]
#define	omegaY   el[7]
#define	omegaZ   el[8]
#define	ro_rg    el[9]
#define	lamda_rg el[10]
#define	mu_rg    el[11]
#define	nu_rg    el[12]
#define	B_    el[13]
#define	L_    el[14]
#define	H_    el[15]

#define TIME Time[0]

#define ALFA angle[0]
#define BETTA angle[1]
#define PITCH angle[2]
#define YAW angle[3]
#define ROLL angle[4]
#define TETA angle[5]
#define PSI angle[6]
#define L42 angle[7]
#define B42 angle[8]

